---
- name: Bootstrap monitor
  hosts: monitor
  tasks: 
    - name: Apt updtate & upgrade
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install podman
      import_tasks: tasks/installpodman.yml

