---
- name: Bootstrap monitor
  hosts: monitor_arcter
  tasks: 
    - name: Apt updtate & upgrade
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install podman
      import_tasks: tasks/installpodman.yml

    - name: Configuring podman
      import_tasks: tasks/podman_config.yml

- name: Install & setup caddy
  hosts: monitor_arcter
  tasks:
    - name: Install Caddy
      import_tasks: tasks/caddy_install.yml
    - name: Stop Caddy
      become: True
      service:
        name: caddy
        state: stopped

#     - name: Copy config
#       become: true
#       copy:
#         src: files/etc/{{ item }}
#         dest: /etc/{{ item }}
#         owner: root
#         group: root
#         mode: 0755
#       with_fileglob:
#       - "/caddy/"

#     - name: Restart service
#       become: True
#       systemd:
#         name: caddy
#         masked: no
#         enabled: yes
#         state: started

# - name: Setup Prometheus
#   hosts: monitor
#   tasks:  
