---
- name: Install GPG
  become: true
  package:
    name: gnupg
    state: present

- name: Add the offical Caddy repository
  become: true
  ansible.builtin.apt_repository:
    repo: {{ item }}
    state: present
  with_items:
  -  deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
  -  deb-src https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main

- name: Add the Caddy GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    state: present

- name: Install Caddy
  become: true
  package:
    name: {{ item }}
    state: present
  with_items:
    - caddy

- name: Copy config
  become: true
  template:
    src: etc/{{ item }}
    dest: /etc/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_fileglob:
  - "/caddy/"

- name: Restart service
  become: True
  systemd:
    name: caddy
    masked: no
    enabled: yes
    state: started


