- name: Copy registries config
  become: true
  copy:
    src: files/etc/containers/registries.conf
    dest: /etc/containers/registries.conf
    owner: root
    group: root
    mode: 0644

- name: Enable podman socket service
  systemd:
    name: podman.socket
    state: started
    enabled: yes

- name: Add read write permission to podman socket
  file:
    path: /var/run/podman/podman.sock
    owner: root
    group: root
    mode: '0664'
