groups:
- name: Blackbox Alerts
  rules:
  - alert: ProbeFailed
    expr: probe_success == 0
    for: 5m
    labels:
      severity: error
    annotations:
      identifier: '{{ $labels.instance }}'
      description: "Probe failed\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: HttpStatusCode
    expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
    for: 5m
    labels:
      severity: error
    annotations:
      identifier: '{{ $labels.instance }}'
      description: "HTTP status code is not 200-399\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: SslCertificateWillExpireSoon
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 5 and probe_sslearliest_cert_expiry - time() > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      identifier: '{{ $labels.instance }}'
      description: "SSL certificate expires in 5 days\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: SslCertificateExpired
    expr: probe_ssl_earliest_cert_expiry - time()  <= 0
    for: 5m
    labels:
      severity: error
    annotations:
      identifier: '{{ $labels.instance }}'
      description: "SSL certificate has expired already\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
