groups:
- name: vmware
  rules:
  - alert: DatastoreIsDown
    expr: vmware_datastore_accessible{dc_name="SCH"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      identifier: '{{ $labels.ds_name }}'
      description: "DataStore: **{{$labels.ds_name}}** is Down!"
  - alert: HostIsDown
    expr: vmware_host_connection_state{dc_name="SCH"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      identifier: '{{ $labels.host_name}}'
      description: "Host: **{{$labels.host_name}}** is Down!"
  - alert: VMCritMemoryUsage
    expr: ((vmware_vm_mem_usage_average{dc_name="SCH"} / 100) >= 95)
    for: 10m
    labels:
      severity: warning
    annotations:
      identifier: '{{ $labels.vm_name}}'
      description: 'Very High memory usage on {{ $labels.vm_name }}: {{ $value | printf "%.2f" }}%'
  - alert: VMCriticalCpuUsage   
    expr: ((vmware_vm_cpu_usage_average{dc_name="SCH"} / 100) >= 95)
    for: 30m
    labels:
      severity: warning
    annotations:
      identifier: '{{ $labels.vm_name}}'
      description: 'Very High CPU usage on {{ $labels.vm_name }}: {{ $value | printf "%.2f" }}%'
