#!/usr/bin/env bash

# Get script's path
DIR="$( cd "$(dirname "$0")" ; pwd -P )"

podman run \
	--rm \
	--name alertmanager \
	--net prometheus \
	--publish 127.0.0.1:9093:9093 \
	--volume $DIR/config.yaml:/etc/amtool/config.yaml \
        --volume $DIR/template/:/etc/alertmanager/template/ \
	prom/alertmanager \
		--config.file=/etc/amtool/config.yaml
