groups:
- name: InstanceStates
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 3m
    labels:
      severity: page
    annotations:
      identifier: '{{ $labels.instance }}'
      description: '{{ $labels.job }} exporter job has been down for more than 5 minutes.'
