groups:
- name: SNMP Warnings
  rules:
  - alert: HighCpuLoad
    expr: avgBusy1 > 80
    for: 1m
    labels:
      severity: warning
    annotations:
      identifier: '{{ $labels.instance }}'
      description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: High Memory Usage on core-net
    expr: >
      (
       sum(ciscoMemoryPoolUsed{facility="core-net"}) by (instance) 
          / (
             sum(ciscoMemoryPoolFree{facility="core-net"}) by (instance) 
             + sum(ciscoMemoryPoolUsed{facility="core-net"}) by (instance)
            )
      ) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      identifier: '{{ $labels.instance }}'
      description: "SCHNET core-net memory usage is HIGH\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: High Memory Usage on server-net
    expr: >
      (
       sum(ciscoMemoryPoolUsed{facility="server-net"}) by (instance)
          / (
             sum(ciscoMemoryPoolFree{facility="server-net"}) by (instance)
             + sum(ciscoMemoryPoolUsed{facility="server-net"}) by (instance)
            )
      ) > 0.9
    for: 5m
    labels:
      severity: warning
    annotations:
      identifier: '{{ $labels.instance }}'
      description: "SCHNET server-net memory usage is HIGH\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"


