# This file is generated. Some meta:
# Time: 2021-06-24T16:53:21.348119
# Host: runner-jzki11j--project-2817-concurrent-0
# Data dir commiter: Miklós Tóth
# Data dir commit hash: 5259e1a0c9a43bc77daf9826e32760bd7b003b65

groups:
- group:
    rules:
    - alert: ExporterUnavailable
      annotations:
        description: "An exporter is unavailable \n  VALUE = {{ $value }}\n  LABELS:\
          \ {{ $labels }}"
        grafana: https://monitoring.kszk.bme.hu/grafna/path-to-dashboard
        identifier: '{{ $labels.instance }}'
      expr: up{service_name="trash"} == 0
      for: 5m
      labels:
        severity: warning
  name: trash@exporter-availability
- group:
    rules:
    - alert: OutOfMemory
      annotations:
        description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value\
          \ }}\n  LABELS: {{ $labels }}"
        grafana: https://monitoring.kszk.bme.hu/grafna/path-to-dashboard
        identifier: '{{ $labels.instance }}'
      expr: node_memory_MemAvailable_bytes{service_name="trash"} / node_memory_MemTotal_bytes{service_name="trash"}
        * 100 < 10
      for: 5m
      labels:
        severity: warning
    - alert: OutOfDiskSpace
      annotations:
        description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n \
          \ LABELS: {{ $labels }}"
        identifier: '{{ $labels.instance }}'
      expr: node_filesystem_free_bytes{mountpoint ="/rootfs"} / node_filesystem_size_bytes{mountpoint
        ="/rootfs"} * 100 < 10
      for: 5m
      labels:
        severity: warning
    - alert: OutOfInodes
      annotations:
        description: "Disk is almost running out of available inodes (< 10% left)\n\
          \  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
        identifier: '{{ $labels.instance }}'
      expr: node_filesystem_files_free{mountpoint ="/rootfs"} / node_filesystem_files{mountpoint
        ="/rootfs"} * 100 < 10
      for: 5m
      labels:
        severity: warning
    - alert: HighCpuLoad
      annotations:
        description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels\
          \ }}"
        identifier: '{{ $labels.instance }}'
      expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m]))
        * 100) > 80
      for: 5m
      labels:
        severity: warning
    - alert: SystemdServiceCrashed
      annotations:
        description: SystemD service crashed on {{ $labels.service_name }}
        identifier: '{{ $labels.name }} crashed'
      expr: node_systemd_unit_state{state="failed"} == 1
      for: 5m
      labels:
        severity: warning
  name: trash@node-general
- group:
    rules:
    - alert: ExporterUnavailable
      annotations:
        description: "An exporter is unavailable \n  VALUE = {{ $value }}\n  LABELS:\
          \ {{ $labels }}"
        grafana: https://monitoring.kszk.bme.hu/grafna/path-to-dashboard
        identifier: '{{ $labels.instance }}'
      expr: up{service_name="noc"} == 0
      for: 5m
      labels:
        severity: warning
  name: noc@exporter-availability
- group:
    rules:
    - alert: OutOfMemory
      annotations:
        description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value\
          \ }}\n  LABELS: {{ $labels }}"
        grafana: https://monitoring.kszk.bme.hu/grafna/path-to-dashboard
        identifier: '{{ $labels.instance }}'
      expr: node_memory_MemAvailable_bytes{service_name="noc"} / node_memory_MemTotal_bytes{service_name="noc"}
        * 100 < 10
      for: 5m
      labels:
        severity: warning
    - alert: OutOfDiskSpace
      annotations:
        description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n \
          \ LABELS: {{ $labels }}"
        identifier: '{{ $labels.instance }}'
      expr: node_filesystem_free_bytes{mountpoint ="/rootfs"} / node_filesystem_size_bytes{mountpoint
        ="/rootfs"} * 100 < 10
      for: 5m
      labels:
        severity: warning
    - alert: OutOfInodes
      annotations:
        description: "Disk is almost running out of available inodes (< 10% left)\n\
          \  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
        identifier: '{{ $labels.instance }}'
      expr: node_filesystem_files_free{mountpoint ="/rootfs"} / node_filesystem_files{mountpoint
        ="/rootfs"} * 100 < 10
      for: 5m
      labels:
        severity: warning
    - alert: HighCpuLoad
      annotations:
        description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels\
          \ }}"
        identifier: '{{ $labels.instance }}'
      expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m]))
        * 100) > 80
      for: 5m
      labels:
        severity: warning
    - alert: SystemdServiceCrashed
      annotations:
        description: SystemD service crashed on {{ $labels.service_name }}
        identifier: '{{ $labels.name }} crashed'
      expr: node_systemd_unit_state{state="failed"} == 1
      for: 5m
      labels:
        severity: warning
  name: noc@node-general
