groups:
- name: Kubernetes
  rules:
  - alert: PersistentVolumeUsagePrediction
    expr: predict_linear(kubelet_volume_stats_available_bytes{}[1h], 12 * 3600) <= 0
    for: 10m
    labels:
      severity: warning
    annotations:
      identifier: '{{ $labels.cluster_name }}/{{ $labels.persistentvolumeclaim }}'
      description: 'The Persistent volume {{ $labels.namespace}}/{{ $labels.persistentvolumeclaim }} will fill up in 12 hours'
